#include "Float.hpp"
#include "FloatRegister.hpp"
#include "quadrature/TanhSinh.hpp"
#include "utils.hpp"
#include <emscripten/bind.h>

EMSCRIPTEN_BINDINGS(my_module)
{
	constant("Nearest", (int)mpfr_rnd_t::MPFR_RNDN);
	constant("TowardZero", (int)mpfr_rnd_t::MPFR_RNDZ);
	constant("TowardInfinity", (int)mpfr_rnd_t::MPFR_RNDU);
	constant("TowardMinusInfinity", (int)mpfr_rnd_t::MPFR_RNDD);
	constant("AwayZero", (int)mpfr_rnd_t::MPFR_RNDA);
	constant("Faithful", (int)mpfr_rnd_t::MPFR_RNDF);

	function("float_register_test", &float_register_test);

	class_<GnuMPFloat>("Float")
		.constructor()
		.constructor<val>()
		// properties
		.property("rounding", &GnuMPFloat::getRounding, &GnuMPFloat::setRounding)
		.property("precision", &GnuMPFloat::getPrecision, &GnuMPFloat::setPrecision)
		.property("exponent", &GnuMPFloat::getExponent, &GnuMPFloat::setExponent)
		.property("sign", &GnuMPFloat::getSign, &GnuMPFloat::setSign)

		// assignments
		.function("set", &GnuMPFloat::set)
		.function("set", select_overload<GnuMPFloat::builder_pattern(const std::string &, int)>(&GnuMPFloat::setString))
		.function("swap", &GnuMPFloat::swap)
		.function("setRounding", &GnuMPFloat::setRounding)
		.function("setPrecision", &GnuMPFloat::setPrecision)
		.function("setExponent", &GnuMPFloat::setExponent)
		.function("setSign", &GnuMPFloat::setSign)

		// conversions
		.function("toString", select_overload<std::string() const>(&GnuMPFloat::toString))
		.function("toString", select_overload<std::string(int) const>(&GnuMPFloat::toString))
		.function("toString", select_overload<std::string(int, int) const>(&GnuMPFloat::toString))
		.function("toNumber", &GnuMPFloat::toNumber)
		.function("valueOf", &GnuMPFloat::toNumber)

		// comparisons
		.function("less", &GnuMPFloat::less)
		.function("less_equal", &GnuMPFloat::less_equal)
		.function("greater", &GnuMPFloat::greater)
		.function("greater_equal", &GnuMPFloat::greater_equal)
		.function("equal", &GnuMPFloat::equal)
		.function("not_equal", &GnuMPFloat::not_equal)

		// arithmetic
		.function("add", &GnuMPFloat::add)
		.function("sub", &GnuMPFloat::sub)
		.function("mul", &GnuMPFloat::mul)
		.function("div", &GnuMPFloat::div)
		.function("neg", &GnuMPFloat::neg)
		.function("dim", &GnuMPFloat::dim)
		.function("sqrt", &GnuMPFloat::sqrt)
		.function("cbrt", &GnuMPFloat::cbrt)
		.function("rec_sqrt", &GnuMPFloat::rec_sqrt)
		.function("root_ui", &GnuMPFloat::root_ui)

		// advanced arithmetic
		.function("fma", &GnuMPFloat::fma)
		.function("fmma", &GnuMPFloat::fmma)
		.function("fms", &GnuMPFloat::fms)
		.function("fmms", &GnuMPFloat::fmms)

		// TRANSCENDENTALS

		.function("log", &GnuMPFloat::log)
		.function("log_ui", &GnuMPFloat::log_ui)
		.function("log2", &GnuMPFloat::log2)
		.function("log10", &GnuMPFloat::log10)
		.function("log1p", &GnuMPFloat::log1p)
		.function("exp", &GnuMPFloat::exp)
		.function("exp2", &GnuMPFloat::exp2)
		.function("exp10", &GnuMPFloat::exp10)
		.function("expm1", &GnuMPFloat::expm1)
		.function("pow", &GnuMPFloat::pow)
		.function("pow_si", &GnuMPFloat::pow_si)
		.function("ui_pow_ui", &GnuMPFloat::ui_pow_ui)
		.function("ui_pow", &GnuMPFloat::ui_pow)
		.function("cos", &GnuMPFloat::cos)
		.function("sin", &GnuMPFloat::sin)
		.function("tan", &GnuMPFloat::tan)
		.function("sec", &GnuMPFloat::sec)
		.function("csc", &GnuMPFloat::csc)
		.function("cot", &GnuMPFloat::cot)
		.function("acos", &GnuMPFloat::acos)
		.function("asin", &GnuMPFloat::asin)
		.function("atan", &GnuMPFloat::atan)
		.function("atan2", &GnuMPFloat::atan2)
		.function("cosh", &GnuMPFloat::cosh)
		.function("sinh", &GnuMPFloat::sinh)
		.function("tanh", &GnuMPFloat::tanh)
		.function("sech", &GnuMPFloat::sech)
		.function("csch", &GnuMPFloat::csch)
		.function("coth", &GnuMPFloat::coth)
		.function("acosh", &GnuMPFloat::acosh)
		.function("asinh", &GnuMPFloat::asinh)
		.function("atanh", &GnuMPFloat::atanh)
		.function("eint", &GnuMPFloat::eint)
		.function("li2", &GnuMPFloat::li2)
		.function("gamma", &GnuMPFloat::gamma)
		.function("gamma_inc", &GnuMPFloat::gamma_inc)
		.function("lngamma", &GnuMPFloat::lngamma)
		.function("lgamma", &GnuMPFloat::lgamma)
		.function("digamma", &GnuMPFloat::digamma)
		.function("beta", &GnuMPFloat::beta)
		.function("zeta", &GnuMPFloat::zeta)
		.function("zeta_ui", &GnuMPFloat::zeta_ui)
		.function("erf", &GnuMPFloat::erf)
		.function("erfc", &GnuMPFloat::erfc)
		.function("j0", &GnuMPFloat::j0)
		.function("j1", &GnuMPFloat::j1)
		.function("jn", &GnuMPFloat::jn)
		.function("y0", &GnuMPFloat::y0)
		.function("y1", &GnuMPFloat::y1)
		.function("yn", &GnuMPFloat::yn)
		.function("agm", &GnuMPFloat::agm)
		.function("ai", &GnuMPFloat::ai)
		.function("const_log2", &GnuMPFloat::const_log2)
		.function("const_pi", &GnuMPFloat::const_pi)
		.function("const_euler", &GnuMPFloat::const_euler)
		.function("const_catalan", &GnuMPFloat::const_catalan)

		// extra stuff
		.function("getMantissaSize", &GnuMPFloat::getMantissaSize)
		.function("getMantissaView", &GnuMPFloat::getMantissaView)
		.function("getRoundingString", &GnuMPFloat::getRoundingString)

		// static stuff
		.class_function("add", &GnuMPFloat::op_add)
		.class_function("sub", &GnuMPFloat::op_sub)
		.class_function("mul", &GnuMPFloat::op_mul)
		.class_function("div", &GnuMPFloat::op_div)
		.class_function("neg", &GnuMPFloat::op_neg)
		.class_function("dim", &GnuMPFloat::op_dim)
		.class_function("sqrt", &GnuMPFloat::op_sqrt)
		.class_function("cbrt", &GnuMPFloat::op_cbrt)
		.class_function("rec_sqrt", &GnuMPFloat::op_rec_sqrt)
		.class_function("root_ui", &GnuMPFloat::op_root_ui)
		.class_function("fac", &GnuMPFloat::op_fac)
		.class_function("fma", &GnuMPFloat::op_fma)
		.class_function("fmma", &GnuMPFloat::op_fmma)
		.class_function("fms", &GnuMPFloat::op_fms)
		.class_function("fmms", &GnuMPFloat::op_fmms)
		.class_function("hypot", &GnuMPFloat::op_hypot)
		.class_function("sum", &GnuMPFloat::op_sum)
		.class_function("dot", &GnuMPFloat::op_dot)

		// TRANSCENDENTALS

		.class_function("log", &GnuMPFloat::op_log)
		.class_function("log_ui", &GnuMPFloat::op_log_ui)
		.class_function("log2", &GnuMPFloat::op_log2)
		.class_function("log10", &GnuMPFloat::op_log10)
		.class_function("log1p", &GnuMPFloat::op_log1p)
		.class_function("exp", &GnuMPFloat::op_exp)
		.class_function("exp2", &GnuMPFloat::op_exp2)
		.class_function("exp10", &GnuMPFloat::op_exp10)
		.class_function("expm1", &GnuMPFloat::op_expm1)
		.class_function("pow", &GnuMPFloat::op_pow)
		.class_function("pow_si", &GnuMPFloat::op_pow_si)
		.class_function("ui_pow_ui", &GnuMPFloat::op_ui_pow_ui)
		.class_function("ui_pow", &GnuMPFloat::op_ui_pow)
		.class_function("cos", &GnuMPFloat::op_cos)
		.class_function("sin", &GnuMPFloat::op_sin)
		.class_function("tan", &GnuMPFloat::op_tan)
		.class_function("sin_cos", &GnuMPFloat::op_sin_cos)
		.class_function("sec", &GnuMPFloat::op_sec)
		.class_function("csc", &GnuMPFloat::op_csc)
		.class_function("cot", &GnuMPFloat::op_cot)
		.class_function("acos", &GnuMPFloat::op_acos)
		.class_function("asin", &GnuMPFloat::op_asin)
		.class_function("atan", &GnuMPFloat::op_atan)
		.class_function("atan2", &GnuMPFloat::op_atan2)
		.class_function("cosh", &GnuMPFloat::op_cosh)
		.class_function("sinh", &GnuMPFloat::op_sinh)
		.class_function("tanh", &GnuMPFloat::op_tanh)
		.class_function("sinh_cosh", &GnuMPFloat::op_sinh_cosh)
		.class_function("sech", &GnuMPFloat::op_sech)
		.class_function("csch", &GnuMPFloat::op_csch)
		.class_function("coth", &GnuMPFloat::op_coth)
		.class_function("acosh", &GnuMPFloat::op_acosh)
		.class_function("asinh", &GnuMPFloat::op_asinh)
		.class_function("atanh", &GnuMPFloat::op_atanh)
		.class_function("eint", &GnuMPFloat::op_eint)
		.class_function("li2", &GnuMPFloat::op_li2)
		.class_function("gamma", &GnuMPFloat::op_gamma)
		.class_function("gamma_inc", &GnuMPFloat::op_gamma_inc)
		.class_function("lngamma", &GnuMPFloat::op_lngamma)
		.class_function("lgamma", &GnuMPFloat::op_lgamma)
		.class_function("digamma", &GnuMPFloat::op_digamma)
		.class_function("beta", &GnuMPFloat::op_beta)
		.class_function("zeta", &GnuMPFloat::op_zeta)
		.class_function("zeta_ui", &GnuMPFloat::op_zeta_ui)
		.class_function("erf", &GnuMPFloat::op_erf)
		.class_function("erfc", &GnuMPFloat::op_erfc)
		.class_function("j0", &GnuMPFloat::op_j0)
		.class_function("j1", &GnuMPFloat::op_j1)
		.class_function("jn", &GnuMPFloat::op_jn)
		.class_function("y0", &GnuMPFloat::op_y0)
		.class_function("y1", &GnuMPFloat::op_y1)
		.class_function("yn", &GnuMPFloat::op_yn)
		.class_function("agm", &GnuMPFloat::op_agm)
		.class_function("ai", &GnuMPFloat::op_ai)
		.class_function("const_log2", &GnuMPFloat::op_const_log2)
		.class_function("const_pi", &GnuMPFloat::op_const_pi)
		.class_function("const_euler", &GnuMPFloat::op_const_euler)
		.class_function("const_catalan", &GnuMPFloat::op_const_catalan)

		// Library functions
		.class_function("get_default_rounding_mode", (int (*)(void))mpfr_get_default_rounding_mode)
		.class_function("get_version", GnuMPFloat::op_get_version)
		.class_function("get_patches", GnuMPFloat::op_get_patches)
		.class_function("buildopt_tls_p", mpfr_buildopt_tls_p)
		.class_function("buildopt_float128_p", mpfr_buildopt_float128_p)
		.class_function("buildopt_decimal_p", mpfr_buildopt_decimal_p)
		.class_function("buildopt_gmpinternals_p", mpfr_buildopt_gmpinternals_p)
		.class_function("buildopt_sharedcache_p", mpfr_buildopt_sharedcache_p)
		.class_function("buildopt_tune_case", GnuMPFloat::op_buildopt_tune_case)
		.class_function("get_emin", mpfr_get_emin)
		.class_function("get_emax", mpfr_get_emax)
		.class_function("get_emin_min", mpfr_get_emin_min)
		.class_function("get_emin_max", mpfr_get_emin_max)
		.class_function("get_emax_min", mpfr_get_emax_min)
		.class_function("get_emax_max", mpfr_get_emax_max)
		.class_function("clear_underflow", mpfr_clear_underflow)
		.class_function("clear_overflow", mpfr_clear_overflow)
		.class_function("clear_divby0", mpfr_clear_divby0)
		.class_function("clear_nanflag", mpfr_clear_nanflag)
		.class_function("clear_inexflag", mpfr_clear_inexflag)
		.class_function("clear_erangeflag", mpfr_clear_erangeflag)
		.class_function("clear_flags", mpfr_clear_flags)
		.class_function("set_underflow", mpfr_set_underflow)
		.class_function("set_overflow", mpfr_set_overflow)
		.class_function("set_divby0", mpfr_set_divby0)
		.class_function("set_nanflag", mpfr_set_nanflag)
		.class_function("set_inexflag", mpfr_set_inexflag)
		.class_function("set_erangeflag", mpfr_set_erangeflag)
		.class_function("underflow_p", mpfr_underflow_p)
		.class_function("overflow_p", mpfr_overflow_p)
		.class_function("divby0_p", mpfr_divby0_p)
		.class_function("nanflag_p", mpfr_nanflag_p)
		.class_function("inexflag_p", mpfr_inexflag_p)
		.class_function("erangeflag_p", mpfr_erangeflag_p)
		.class_function("flags_save", mpfr_flags_save)
		.class_function("free_pool", mpfr_free_pool)
		.class_function("free_cache", mpfr_free_cache)

		.class_function("sqr", GnuMPFloat::op_sqr)
		.class_function("cmp", GnuMPFloat::op_cmp)
		.class_function("cmp_ui", GnuMPFloat::op_cmp_ui)
		.class_function("cmp_si", GnuMPFloat::op_cmp_si)
		.class_function("cmp_d", GnuMPFloat::op_cmp_d)
		.class_function("cmp_ui_2exp", GnuMPFloat::op_cmp_ui_2exp)
		.class_function("cmp_si_2exp", GnuMPFloat::op_cmp_si_2exp)
		.class_function("cmpabs", GnuMPFloat::op_cmpabs)
		.class_function("cmpabs_ui", GnuMPFloat::op_cmpabs_ui)
		.class_function("nan_p", GnuMPFloat::op_nan_p)
		.class_function("inf_p", GnuMPFloat::op_inf_p)
		.class_function("number_p", GnuMPFloat::op_number_p)
		.class_function("zero_p", GnuMPFloat::op_zero_p)
		.class_function("regular_p", GnuMPFloat::op_regular_p)
		.class_function("sgn", GnuMPFloat::op_sgn)
		.class_function("greater_p", GnuMPFloat::op_greater_p)
		.class_function("greaterequal_p", GnuMPFloat::op_greaterequal_p)
		.class_function("less_p", GnuMPFloat::op_less_p)
		.class_function("lessequal_p", GnuMPFloat::op_lessequal_p)
		.class_function("equal_p", GnuMPFloat::op_equal_p)
		.class_function("lessgreater_p", GnuMPFloat::op_lessgreater_p)
		.class_function("unordered_p", GnuMPFloat::op_unordered_p)
		.class_function("total_order_p", GnuMPFloat::op_total_order_p)
		.class_function("frac", GnuMPFloat::op_frac)
		.class_function("modf", GnuMPFloat::op_modf)
		.class_function("fmod", GnuMPFloat::op_fmod)
		.class_function("fmodquo", GnuMPFloat::op_fmodquo)
		.class_function("remainder", GnuMPFloat::op_remainder)
		.class_function("remquo", GnuMPFloat::op_remquo)
		.class_function("set_default_rounding_mode", GnuMPFloat::op_set_default_rounding_mode)
		.class_function("prec_round", GnuMPFloat::op_prec_round)
		.class_function("can_round", GnuMPFloat::op_can_round)
		.class_function("min_prec", GnuMPFloat::op_min_prec)
		.class_function("nexttoward", GnuMPFloat::op_nexttoward)
		.class_function("nextabove", GnuMPFloat::op_nextabove)
		.class_function("nextbelow", GnuMPFloat::op_nextbelow)
		.class_function("min", GnuMPFloat::op_min)
		.class_function("max", GnuMPFloat::op_max)
		//.class_function("nrandom", Float::op_nrandom)
		//.class_function("grandom", Float::op_grandom)
		//.class_function("erandom", Float::op_erandom)
		.class_function("get_exp", GnuMPFloat::op_get_exp)
		.class_function("set_exp", GnuMPFloat::op_set_exp)
		.class_function("signbit", GnuMPFloat::op_signbit)
		.class_function("setsign", GnuMPFloat::op_setsign)
		.class_function("copysign", GnuMPFloat::op_copysign)
		.class_function("set_emin", GnuMPFloat::op_set_emin)
		.class_function("set_emax", GnuMPFloat::op_set_emax)
		.class_function("check_range", GnuMPFloat::op_check_range)
		.class_function("subnormalize", GnuMPFloat::op_subnormalize)
		.class_function("flags_clear", GnuMPFloat::op_flags_clear)
		.class_function("flags_set", GnuMPFloat::op_flags_set)
		.class_function("flags_test", GnuMPFloat::op_flags_test)
		.class_function("flags_restore", GnuMPFloat::op_flags_restore);

	/*class_<TanhSinh>("TanhSinh")
		.constructor<Float::prec_t>()
		.constructor<Float::prec_t, int>()
		.function("compile", &TanhSinh::compile)
		.function("integrate", &TanhSinh::integrate)
		//.function("setIntegrand", &TanhSinh::setIntegrand)
		.function("setBounds", &TanhSinh::setBounds)
		.function("setUpperBound", &TanhSinh::setUpperBound)
		.function("getUpperBound", &TanhSinh::getUpperBound)
		.function("setLowerBound", &TanhSinh::setLowerBound)
		.function("getLowerBound", &TanhSinh::getLowerBound)
		.function("isConvergentError", &TanhSinh::isConvergentError)
		.function("getAbsoluteErrorApprox", &TanhSinh::getAbsoluteErrorApprox)
		.function("getRelativeErrorExponent", &TanhSinh::getRelativeErrorExponent)
		.function("getIntegralApprox", &TanhSinh::getIntegralApprox);*/
};